name: Broken link identifier

# Three ways to trigger this link checker:
#  1. Automatically, once a week on a regular schedule
#  2. Manually through the GitHub actions GUI
#  3. Automatically, on pushes to the main branch
on:
  schedule:
    # Run at 8:30am (EST) on mondays - GitHub cron jobs are specified in UTC
    - cron: "30 13 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      # Check out the main branch - we'll check all the markdown files
      - uses: actions/checkout@v6.0.1
        with:
          ref: main
          path: heasarc-tutorials-main

      # The point of this action - running a link checker on the files in the main branch.
      - name: Find broken links [HEASARC-tutorials]
        id: lychee
        uses: lycheeverse/lychee-action@v2.7.0
        with:
          args: --root-dir "$(pwd)" --accept '100..=103,200..=299,403' --verbose --no-progress './**/*.md' './**/*.html' --exclude-path '_static'
          fail: true
          format: markdown
          workingDirectory: heasarc-tutorials-main
          failIfEmpty: true
