name: Redirect executed notebook CircleCI artifacts
on: [status]

permissions: read-all

jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    if: "${{ github.event.context == 'ci/circleci: pr-build-docs' }}"
    permissions:
      statuses: write
    name: Use CircleCI artifact redirector to link executed notebooks

    steps:
      - name: Run executed notebook redirector
        id: step1
        uses: DavidT3/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.HEASARC_TUTORIALS_CIRCLECI_TOKEN }}
          artifact-path: 0/artifacts/executed_notebooks/nb_index.html
          circleci-jobs: pr-build-docs
          job-title: "**Access executed Jupyter notebooks here!**"
          domain: circle.scientific-python.dev
